spring.datasource.url=jdbc:h2:mem:bookdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.web.resources.add-mappings=false

spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

logging.level.com.epam.rd.autocode.spring.project=INFO
logging.level.org.springframework=WARN
logging.level.org.springframework.web=WARN
logging.level.org.springframework.security=WARN
logging.level.org.springframework.boot=WARN

logging.level.org.hibernate=WARN
logging.level.org.hibernate.SQL=WARN
logging.level.org.jpa=WARN

logging.level.org.apache.catalina=WARN
logging.level.org.apache.coyote=WARN

spring.messages.basename=i18n/messages
spring.messages.encoding=UTF-8
spring.messages.cache-duration=3600

server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12

server.ssl.key-store-password=${SSL_KEYSTORE_PASSWORD}
server.ssl.key-password=${SSL_KEY_PASSWORD}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=bookservice

# --- Security & JWT ---
security.login.max-attempts=5
security.login.lock-duration-minutes=15

application.security.jwt.secret-key=${JWT_SECRET_KEY}
application.security.jwt.expiration=900000
application.security.jwt.refresh-token.expiration=604800000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
# Пошта та пароль додатка
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true